workbookName: "ICINoHIStreams.xlsx"
modelbookName: "ICINoHIModels9-24.xlsx"
streamTitle: "ICI Methanol Streams"
modelTitle: "Methanol ICI Syntex Quench"
calculationBlocks: [Heater, HXFlux, Flash2, RPlug]
computer: [preperation, s1,s2,s3]
test: 3
